# Generated by Django 5.1.6 on 2025-03-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_cv_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaentrevista',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
