# Generated by Django 5.1.6 on 2025-03-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_respuestaentrevista_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='promedio_puntuacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='resultado_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
